server:
  port: 8082
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products
    username: postgres
    password: marisol1995
    pool:
      max-size: 10
      max-create-connection-time: 10s
  jpa:
    show-sql: true
    mapping-resources:
    - com/mh/erp/products/infrastructure/postgredb/daos/ProductRepository.xml